using ImpressDev.Migrations;
using ImpressDev.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace ImpressDev.DAL
{
    public class ImpressDevInitializer : MigrateDatabaseToLatestVersion<ImpressDevContext, Configuration>
    {
        public static void SeedImpressDevData(ImpressDevContext context)
        {
            var categories = new List<Category>
            {
                new Category() { CategoryId = 1, Name = "SQL" },
                new Category() { CategoryId = 2, Name = "Swift" },
                new Category() { CategoryId = 3, Name = "TypeScript" },
                new Category() { CategoryId = 4, Name = "Java" },
                new Category() { CategoryId = 5, Name = "JavaScript" },
                new Category() { CategoryId = 6, Name = "PHP" },
                new Category() { CategoryId = 7, Name = "Python" },
                new Category() { CategoryId = 8, Name = "VisualBasic" }
            };

            categories.ForEach(x => context.Categories.AddOrUpdate(x));
            context.SaveChanges();

            var books = new List<Book>
            {
                new Book() { BookId = 1, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 2, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 3, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 4, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 5, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 6, CategoryId = 1, Title = "Kurs SQL", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "sql.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 7, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 8, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 9, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 10, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 11, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 12, CategoryId = 2, Title = "Kurs Swift", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "swift.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 13, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 14, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 15, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 16, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 17, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 18, CategoryId = 3, Title = "Kurs TypeScript", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "typescript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 19, CategoryId = 4, Title = "Kurs Java", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 20, CategoryId = 4, Title = "Kurs Java", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 21, CategoryId = 4, Title = "Kurs Java", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 22, CategoryId = 4, Title = "Kurs Java", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 23, CategoryId = 4, Title = "Kurs Java", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 24, CategoryId = 4, Title = "Kurs Java", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "java.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 25, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 26, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 27, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 28, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 29, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 30, CategoryId = 5, Title = "Kurs JavaScript", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "javascript.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 31, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 32, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 33, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 34, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 35, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 36, CategoryId = 6, Title = "Kurs PHP", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "php.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 37, CategoryId = 7, Title = "Kurs Python", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 38, CategoryId = 7, Title = "Kurs Python", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 39, CategoryId = 7, Title = "Kurs Python", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 40, CategoryId = 7, Title = "Kurs Python", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 41, CategoryId = 7, Title = "Kurs Python", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 42, CategoryId = 7, Title = "Kurs Python", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "python.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },

                new Book() { BookId = 43, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Teoria", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 46, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 44, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Teoria", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 42, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 45, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Teoria", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 54, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 46, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Praktyka", Level = "Poziom 1/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 39, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 47, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Praktyka", Level = "Poziom 2/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 45, Bestseller = false, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
                new Book() { BookId = 48, CategoryId = 8, Title = "Kurs VisualBasic", SubTitle = "Praktyka", Level = "Poziom 3/3", Author = "Alex Jones", PublishingHouse = "ImpressDev", Cover = "Oprawa twarda", Pages = "452", Price = 49, Bestseller = true, Inaccessible = false, DateAdded = DateTime.Now, PhotoSource = "visualbasic.jpg", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." },
            };
            books.ForEach(x => context.Books.AddOrUpdate(x));
            context.SaveChanges();
        }
    }
}